### ISSUE TITLE
Add methods to add and subtract ingredient quantities in the Ingredient model

### ISSUE THREAD

**Issue by amymalia** [KaleWithFriends/KaleWithFriends#16]
To help with updating farmers info

**Comment by wnalle** [comment]
Don't worry about this until after I'm done with the persistent storage models.

**Comment by amymalia** [comment]
Ok. I implemented this using the built in db awhile ago but it doesnt work correctly yet. I just won't work on it anymore until the new db is done.

**Comment by amymalia** [comment]
Works with built in db. Will create new issue once we merge with the persistant db
